[workspace]
members = ["orchestrator", "cosmos_gravity", "ethereum_gravity", "gravity_utils", "proto_build", "test_runner", "gravity_proto", "relayer", "register_delegate_keys", "gbt"]
default-members = ["gbt"]


[patch.crates-io]
