# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Solidity contract build and test

on:
  push:
    branches: [master, althea-peggy]
  pull_request:
    branches: [master, althea-peggy]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Build and test Solidity contracts
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd solidity && npm ci
      - run: cd solidity && npm run typechain
      - run: cd solidity && npm run evm &
      - run: cd solidity && npm run test
